### ISSUE TITLE
Convert Project Euler tasks to in-house challenges

### ISSUE THREAD

**Issue by timolawl** [freeCodeCamp/arcade-mode#19]
We currently need help with converting Project Euler tasks into full-fledged in-house challenges. This mostly involves adding a solution to the challenge.

**Details:**
Please refer to [this path](https://github.com/freeCodeCamp/arcade-mode/tree/master/client/scripts/challenges/projecteuler).
- Raw Project Euler tasks are located in the `raw` directory.
- Formatted challenges go into the `formatted` directory; the subdirectory depends on the hundreds-digit (e.g., Problem 53 would go into folder `001_to_100`).

The format you see is the in-house format we use to process the challenges into one json file.

**What needs to be done:**
- A solution under the `/// solutions:` header (it should have the same function name as in the `challengeSeed`)
- An estimated difficulty rating between 1 (easiest) and 9 (hardest)

For reference, refer to the finished [Problem 2: Even Fibonacci numbers](https://github.com/freeCodeCamp/arcade-mode/blob/master/client/scripts/challenges/projecteuler/formatted/001_to_100/Problem%20002:%20Even%20Fibonacci%20numbers.js).

Overall progress is updated at [this spreadsheet](https://docs.google.com/spreadsheets/d/1b_wMIaKR-gA0tD6ADQfDjDT5BBWaUsQyIPP0TS6o7is/edit?usp=sharing).

Please let us know if you would like to get involved at our [Gitter room](https://gitter.im/FreeCodeCamp/arcade-mode).

Thank you all for the help!

**Comment by vikramnr** [comment]
@timolawl  I would like to contribute to this issue.  But is there any standard solutions for each problem.  Because they might be better solution then my solution? What if that's the case?

**Comment by timolawl** [comment]
@vikramnr Sorry for the long delay. You can use your own solution or a solution you find elsewhere. If you find a more efficient solution, that is preferable, but any adequate sensible solution will do. If it's your own, then it's a 2-in-1 as you will have the opportunity to practice your coding skills as well!

**Comment by vikramnr** [comment]
@timolawl, @QuincyLarson  I'm not sure about the current project roadmap for this but if this is something you guys want to create I'll be happy to give it a try.
