### ISSUE TITLE
Expand Contributing.md to include additional relevant details

### ISSUE THREAD

**Issue by QuincyLarson** [freeCodeCamp/arcade-mode#22]
Currently the [Contributing.md](https://github.com/freeCodeCamp/arcade-mode/blob/master/CONTRIBUTING.md) file does a good job of covering how to get set up, but is should also:
1. Include an embed of the video demo Tuomas recorded
2. Include a link to the spreadsheet (read-only) for people to browse to get a better idea of what it's for, and an explanation of what the spreadsheet is.
3. You might want to clarify the role of Arcade Mode - basically, a stand alone app that will soon become the freeCodeCamp coding interview prep section

**Comment by timolawl** [comment]
The Contributing guide has been updated for points 2 and 3.

**Comment by QuincyLarson** [comment]
@timolawl Awesome! Thanks!
