### ISSUE TITLE
Error: Timeout of 2000ms exceeded

### ISSUE THREAD

**Issue by NitronR** [freeCodeCamp/arcade-mode#31]
For Rosetta Code problem : Euler's sum of powers conjecture, it gives this error - Error: Timeout of 2000ms exceeded.

**Comment by tpoikela** [comment]
This means that tests are taking too long to run. You should then reduce the runtime by changing input parameters to the function. 

Generally, they should take much less than 2000ms, otherwise this will affect negatively the user experience.

**Comment by NitronR** [comment]
Thanks for the suggestion, but the problem requires more than 2000ms to give the output even for the minimum input parameter of 250.

**Comment by NitronR** [comment]
Should we hold the problem or exclude it?

**Comment by timolawl** [comment]
@NitronR We can put this problem on hold, but we most likely will just skip its inclusion as we have plenty of other challenges.

**Comment by NitronR** [comment]
@timolawl Ok I will put it on hold for now. Thanks for the reply!!
